import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { ConnectButton } from '@suiet/wallet-kit';
import {useWallet} from '@suiet/wallet-kit';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })
let objectID = "";

export default function Home() {

  const wallet = useWallet();
  
  async function handleSignAndExecuteTx() {

    console.log("Transacting")
        if (!wallet.connected) {
          alert("wallet not connected");
          return
        }
    try {
      const resData = await wallet.signAndExecuteTransaction({
        transaction: {
          kind: 'moveCall',
          data: {
            packageObjectId: '0x2',
            module: 'devnet_nft',
            function: 'mint',
            typeArguments: [],
            arguments: [
              "Martian Wallet",
              "The most trusted wallet in the Move Ecosystem",
              "https://moveecosystem.com/wp-content/uploads/2022/12/martian.gif"
            ],
            gasBudget: 10000,
          }
        }
      });
      console.log('nft minted successfully!', resData);
      if (resData.EffectsCert) {
        objectID = resData?.EffectsCert?.effects?.effects?.created[0]?.reference?.objectId; 
      }
      else {
        objectID = resData?.effects?.created[0]?.reference?.objectId;  
      }
      console.log(objectID);
    } catch (e) {
        console.error('nft mint failed', e);
    } 
    var url = "https://explorer.sui.io/objects/" + encodeURIComponent(objectID);
    document.getElementById("explorer-link").href = url;
    document.getElementById('success-msg').style.display = "block";
    document.getElementById('mint-btn').style.display = "none";
  }

  useEffect (() => { 
    const spaceAudio = new Audio('../spaceaudio.wav');
    if (!wallet.connected) {
      document.getElementById('revealed').style.opacity=0.05;
      document.getElementsByClassName('Home_main__nLjiQ')[0].style.backgroundColor=null; 
      document.getElementById('validated-canvas-overlay').style.width="355px";
      document.getElementById('validated-canvas-overlay').style.height="355px";
      spaceAudio.pause();
      return;   
    }
    document.getElementsByClassName('Home_main__nLjiQ')[0].style.backgroundColor="black";
    document.getElementById('revealed').style.opacity=1;
    document.getElementById('validated-canvas-overlay').style.width="400px";
    document.getElementById('validated-canvas-overlay').style.height="400px";
    spaceAudio.play();
  }, [wallet.connected])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>  
            Mint with <a href="https://martianwallet.xyz/">Martian Wallet</a> <br></br>for Martian OG Consideration
          </p>
          <div>
            <ConnectButton>Connect to Mint NFT</ConnectButton>
            
          </div>
        </div>
        <div id="revealed">
          
        <div className={styles.center}>  
            <div className='wkit-connected-container'>
              <button 
                className="wkit-connected-button" 
                id="success-msg"
              >
                <p>Success! View NFT <a href="#" id="explorer-link">Here</a></p>
              </button>
            </div>
          </div>

          <div className={styles.center}>
            <div id="canvas-container">
              <div id="sound-canvas">
                <Image 
                  id="validated-canvas-overlay" 
                  src="/martian.gif"
                  width={355}
                  height={355}
                  alt="Martian NFT"
                /> 
              </div>
            </div>
          </div>
        

  

          <div className={styles.center}>
            <div className='wkit-connected-container'>
              <div className='wkit-connected-container'>
                <button 
                  className="wkit-connected-button" 
                  onClick={handleSignAndExecuteTx}
                  id="mint-btn"
                >
                  Mint NFT ✠
                </button>
              </div>  
            </div>
          </div>

        </div>
      </main>
    </>
  )
}
